# name: shelterbelts
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - python=3.11
#   - pip
#   - pip:
#       - -e .[dev]

name: shelterbelts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pdal  # Need to install pdal with conda instead of pip
  - python-pdal
  - rasterio
  - pip
  - pip:
      - -e .[dev]