import time

from shelterbelts.classifications.lidar import lidar
from shelterbelts.classifications.sentinel_dea import download_ds2  # Couldn't decide if this belonged in the 'APIs' folder or 'classifications' 

def test_basic():
    """Quickly test all the functions"""
    lidar('data/Young201709-LID1-C3-AHD_6306194_55_0002_0002.laz', outdir='outdir', stub='g2_26729', resolution=1, category5=True)
    download_ds2('outdir/g2_26729_woodyveg_res1_cat5.tif', start_date="2020-01-01", end_date="2021-01-01", outdir="outdir")


def test_lidar():
    """More comprehensive lidar tests: 2 resolutions, 2 heights, with or without category_5, binary or percent cover"""
    sample_laz = 'data/Young201709-LID1-C3-AHD_6306194_55_0002_0002.laz'  # Downloaded this from ELVIS

    # I got a bit lazy with the tests by just running the code
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=1, category5=True)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=10, category5=True)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=1, height_threshold=2, category5=False)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=1, height_threshold=5, category5=False)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=10, height_threshold=2, category5=False)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=10, category5=True, binary=False)
    lidar(sample_laz, outdir='outdir', stub='g2_26729', resolution=10, height_threshold=2, category5=False, binary=False)

def test_sentinel():
    """More comprehensive tests for sentinel imagery from the DEA STAC API: 2x year ranges"""
    sample_tif = 'outdir/g2_26729_woodyveg_res1_cat5.tif'  # Generated by the test_lidar
    download_ds2(sample_tif, start_date="2020-06-01", end_date="2021-06-01", outdir="outdir")


# Need to redo these with the new tile_csv and tile_csvs inputs
# def test_merging(): 
#     """More comprehensive tests for the merging: 2x radius, 2x spacing"""
#     sentinel_tile = 'outdir/g2_26729_woodyveg_res1_cat5_ds2.pkl'
#     tile_csv(sentinel_tile, tree_folder='outdir', outdir='outdir', radius=4, spacing=10, double_f=False)
#     tile_csv(sentinel_tile, tree_folder='outdir', outdir='outdir', radius=1, spacing=10, double_f=False)
#     tile_csv(sentinel_tile, tree_folder='outdir', outdir='outdir', radius=4, spacing=1, double_f=False)


if __name__ == '__main__':
    print("testing classifications")
    start = time.time()

    # test_basic()
    test_lidar()
    test_sentinel()

    print(f"tests successfully completed in {time.time() - start} seconds")