#!/bin/bash
#PBS -N alphaearth
#PBS -l mem=4GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -P xe2
#PBS -l walltime=10:00:00
#PBS -l storage=gdata/xe2
#PBS -q copyq
#PBS -j oe


# Print out input variables to the error log
# subfolder=/scratch/xe2/cb8590/Nick_Aus_treecover_10m

source /g/data/xe2/cb8590/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xe2/cb8590/miniconda/envs/shelterbelts

wd=/home/147/cb8590/Projects/shelterbelts/src/shelterbelts/classifications
cd $wd

# Run the script
# python3 alpha_earth.py /g/data/xe2/cb8590/Nick_Aus_treecover_10m --outdir /scratch/xe2/cb8590/alphaearth --limit 10 --authenticate
year=2024

echo "Running alphaearth.pbs with subfolder $subfolder for year $year"
python3 alpha_earth.py $subfolder --outdir /scratch/xe2/cb8590/alphaearth_pickle --authenticate --start_date ${year}-01-01 --end_date $((year + 1))-01-01