#!/bin/bash
#PBS -N bounding_boxes
#PBS -l mem=32GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -P xe2
#PBS -l walltime=10:00:00
#PBS -l storage=gdata/xe2+gdata/v10+gdata/ka08
#PBS -q normal

echo "Starting bounding_boxes.pbs"

# Change working directory
wd=/home/147/cb8590/Projects/shelterbelts
cd $wd

# Setup DEA environment modules for running the Python script. Need to add the v10 storage if I want to use this environment. Don't actually need this environment, but it's convenient since the next step for sentinel_imagery downloading will use this environment.
module use /g/data/v10/public/modules/modulefiles
module load dea/20231204

# year=2024
# folder=/scratch/xe2/cb8590/barra_trees_s4_aus_noxy_df_4326_${year}/subfolders/
# python3 src/shelterbelts/classifications/bounding_boxes.py $folder --crs EPSG:3857

folder=/scratch/xe2/cb8590/barra_trees_s4_2020_actnsw_4326_weightings_median/expanded/linear_tifs_lat_34_lon_148_default_percentmethod
python3 src/shelterbelts/classifications/bounding_boxes.py $folder --crs EPSG:3857 --filetype linear_categories.tif
