#!/bin/bash
#PBS -N expand_tifs
#PBS -l mem=4GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -P xe2
#PBS -l walltime=02:00:00
#PBS -l storage=gdata/xe2+gdata/ob53
#PBS -q normal

# stub=lat_34_lon_144
# folder_year=barra_trees_s4_2024

folder_year=barra_trees_s4_aus_4326_weightings_median_2020
stub=lat_32_lon_148
gpkg=/scratch/xe2/cb8590/barra_trees_s4_aus_4326_weightings_median_2020/subfolders/barra_trees_s4_aus_4326_weightings_median_2020_subfolders__footprints.gpkg

folder_to_expand=/scratch/xe2/cb8590/$folder_year/subfolders/$stub
folder_merged=/scratch/xe2/cb8590/$folder_year/subfolders 
outdir=/scratch/xe2/cb8590/$folder_year/expanded

echo "Starting expand_tif.pbs for folder_to_expand $folder_to_expand, outdir $outdir"

# Change working directory
cd /home/147/cb8590/Projects/shelterbelts/src/shelterbelts/indices

# Load the conda environment
source /g/data/xe2/cb8590/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xe2/cb8590/miniconda/envs/shelterbelts

# Run the script
python expand_tifs.py --folder_to_expand $folder_to_expand --folder_merged $folder_merged --outdir $outdir --gpkg $gpkg