#!/bin/bash
#PBS -N indices_copy
#PBS -l mem=4GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -P xe2
#PBS -l walltime=00:30:00
#PBS -l storage=gdata/xe2+gdata/ob53
#PBS -q normal

export GDAL_CACHEMAX=64
export GDAL_NUM_THREADS=1

# Load the conda environment
# cd /home/147/cb8590/Projects/shelterbelts/src/shelterbelts/indices
cd /home/147/cb8590/Projects/shelterbelts/notebooks
source /g/data/xe2/cb8590/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xe2/cb8590/miniconda/envs/shelterbelts

python demo_all_indices.py
