#!/bin/bash


#####################
# Re-running on the files that had lidar zips with 0 filesize

# ## Run lidar.pbs on a single folder
# BASE_FOLDER="/scratch/xe2/cb8590/lidar/DATA_587085"
# # laz_folder="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD/subfolder_1"
# laz_folder="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD/subfolder_1"
# CHM_FOLDER="$BASE_FOLDER/chm"
# qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs


##############

# # Running on a single ACT LiDAR subfolder
# laz_folder="/scratch/xe2/cb8590/ACTGOV_LiDAR_2025/LAZ/Area_B/subfolder_1"
# CHM_FOLDER="/scratch/xe2/cb8590/ACTGOV_my_processing"
# qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs

##################

## Run the lidar.pbs on every subfolder generated by ./distribute.sh
# LAZ_FOLDERS="/scratch/xe2/cb8590/ACTGOV_LiDAR_2025/LAZ/Area_B"
LAZ_FOLDERS="/scratch/xe2/cb8590/ACTGOV_LiDAR_2025/LAZ/Urban_A"
CHM_FOLDER="/scratch/xe2/cb8590/ACTGOV_my_processing"

for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
    echo "Submitting job for $laz_folder"
    qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
done


# NSW_folders=(DATA_587065 DATA_587068 DATA_587081 DATA_587083 DATA_587085 \
#              DATA_587109 DATA_587116 DATA_587122 DATA_587124 DATA_587133)  # First test batch where the region sizes were too big (0.5 degrees), so some of the zips didn't download correctly
# NSW_folders=(DATA_717827 DATA_717837 DATA_717833 DATA_717831 DATA_717829 DATA_717843 DATA_717840 DATA_717850 DATA_717847 \
#              DATA_717859 DATA_717863 DATA_717865 DATA_717856 DATA_717861 DATA_717867 DATA_717871)  # Second test batch of 30km tiles
# NSW_folders=(DATA_722869 DATA_722875 DATA_722867 DATA_722858 DATA_722873 DATA_722860 DATA_722878 DATA_722855 DATA_722850 DATA_722847 \
#              DATA_722834 DATA_722832 DATA_722830 DATA_722836 DATA_722839 DATA_722819 DATA_722842 DATA_722827 DATA_722822 DATA_722824 \
#              DATA_722803 DATA_722800 DATA_722798 DATA_722806 DATA_722815 DATA_722810 DATA_722787 DATA_722796 DATA_722792 DATA_722785 \
#              DATA_722777 DATA_722757 DATA_722773 DATA_722770 DATA_722768 DATA_722779 DATA_722759 DATA_722766 DATA_722764 DATA_722762 \
#              DATA_722744 DATA_722747 DATA_722731 DATA_722751 DATA_722729 DATA_722739 DATA_722754 DATA_722734 DATA_722725 DATA_722736 \
#              DATA_722717 DATA_722720 DATA_722723 DATA_722706 DATA_722712 DATA_722701 DATA_722710 DATA_722703 DATA_722708 DATA_722698 \
#              DATA_722692 DATA_722694 DATA_722690 DATA_722696 DATA_722682 DATA_722686 DATA_722684 DATA_722677 DATA_722671 DATA_722674 \
#              DATA_722654 DATA_722647 DATA_722657 DATA_722651 DATA_722668 DATA_722644 DATA_722664 DATA_722660 DATA_722642 DATA_722640 \
#              DATA_722617 DATA_722621 DATA_722611 DATA_722626 DATA_722631 DATA_722633 DATA_722613 DATA_722606 DATA_722589 DATA_722603 \
#              DATA_722600 DATA_722591 DATA_722597 DATA_722581 DATA_722587 DATA_722579 DATA_722583 DATA_722585 DATA_722577 DATA_722575)  # 10x10 area. Took about 10 mins to copy these numbers from my emails.


# for nsw_folder in "${NSW_folders[@]}"; do
#     # BASE_FOLDER="/scratch/xe2/cb8590/lidar/$nsw_folder"
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar_30km_old/$nsw_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done


# ## The rest of the ACT folders
# # ACT_folders=(DATA_587116 DATA_587120 DATA_587127)
# # ACT_folders=(DATA_727325 DATA_727319 DATA_727332 DATA_727334 DATA_727323 DATA_727327 DATA_727330 DATA_727317 DATA_727315 DATA_727321)  # Actually ACT folders

# for act_folder in "${ACT_folders[@]}"; do
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar/$act_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done
