#!/bin/bash


#####################
# Re-running on the files that had lidar zips with 0 filesize

# ## Run lidar.pbs on a single folder
# BASE_FOLDER="/scratch/xe2/cb8590/lidar/DATA_587085"
# # laz_folder="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD/subfolder_1"
# laz_folder="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD/subfolder_1"
# CHM_FOLDER="$BASE_FOLDER/chm"
# qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs


##############

# # Running on a single ACT LiDAR subfolder
# laz_folder="/scratch/xe2/cb8590/ACTGOV_LiDAR_2025/LAZ/Area_B/subfolder_1"
# CHM_FOLDER="/scratch/xe2/cb8590/ACTGOV_my_processing"
# qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs

##################

## Run the lidar.pbs on every subfolder generated by ./distribute.sh
LAZ_FOLDERS="/scratch/xe2/cb8590/ACTGOV_LiDAR_2025/LAZ/Area_B"
CHM_FOLDER="/scratch/xe2/cb8590/ACTGOV_my_processing"

for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
    echo "Submitting job for $laz_folder"
    qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
done


# NSW_folders=(DATA_587065 DATA_587068 DATA_587081 DATA_587083 DATA_587085 \
#              DATA_587109 DATA_587116 DATA_587122 DATA_587124 DATA_587133)  # First test batch where the region sizes were too big (0.5 degrees), so some of the zips didn't download correctly
# NSW_folders=(DATA_717827 DATA_717837 DATA_717833 DATA_717831 DATA_717829 DATA_717843 DATA_717840 DATA_717850 DATA_717847 \
#              DATA_717859 DATA_717863 DATA_717865 DATA_717856 DATA_717861 DATA_717867 DATA_717871)  # Second test batch of 30km tiles
# for nsw_folder in "${NSW_folders[@]}"; do
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar/$nsw_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done


## The rest of the ACT folders
# ACT_folders=(DATA_587116 DATA_587120 DATA_587127)
# for act_folder in "${ACT_folders[@]}"; do
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar/$act_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done
