#!/bin/bash

## Run lidar.pbs on a single folder
BASE_FOLDER="/scratch/xe2/cb8590/lidar/DATA_587000"
laz_folder="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD/"
CHM_FOLDER="$BASE_FOLDER/chm"
qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs


## Run the lidar.pbs on every subfolder generated by ./distribute.sh
# BASE_FOLDER="/scratch/xe2/cb8590/lidar/DATA_586204"
# LAZ_FOLDERS="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD"
# CHM_FOLDER="$BASE_FOLDER/chm"

# for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#     echo "Submitting job for $laz_folder"
#     qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
# done


# The rest of the NSW folders
# NSW_folders=(DATA_587065 DATA_587068 DATA_587081 DATA_587083 DATA_587085 \
#              DATA_587109 DATA_587116 DATA_587122 DATA_587124 DATA_587133)
# for nsw_folder in "${NSW_folders[@]}"; do
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar/$nsw_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/NSW Government - Spatial Services/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done


## The rest of the ACT folders
# ACT_folders=(DATA_587116 DATA_587120 DATA_587127)
# for act_folder in "${ACT_folders[@]}"; do
#     BASE_FOLDER="/scratch/xe2/cb8590/lidar/$act_folder"
#     LAZ_FOLDERS="$BASE_FOLDER/laz_files/ACT Government/Point Clouds/AHD"
#     CHM_FOLDER="$BASE_FOLDER/chm"

#     for laz_folder in "$LAZ_FOLDERS"/subfolder_*; do
#         echo "Submitting job for $laz_folder"
#         qsub -v LAZ_FOLDER="$laz_folder",CHM_FOLDER="$CHM_FOLDER" lidar.pbs
#     done
# done
