#!/bin/bash
#PBS -N merge_lidar
#PBS -l mem=16GB
#PBS -l ncpus=1
#PBS -l jobfs=1GB
#PBS -P xe2
#PBS -l walltime=10:00:00
#PBS -l storage=gdata/xe2
#PBS -q normal

# base_dir=/scratch/xe2/cb8590/barra_trees_s4_2024/subfolders/lat_28_lon_140
# base_dir=/scratch/xe2/cb8590/barra_trees_s4_2024/expanded/linear_tifs_lat_36_lon_144_cropfix
# base_dir=/scratch/xe2/cb8590/barra_trees_s4_2018_actnsw_4326/expanded/opportunities_lat_32_lon_148
# base_dir="/scratch/xe2/cb8590/barra_trees_s4_aus_4326_weightings_median_2020/subfolders/lat_28_lon_146"
# base_dir=/scratch/xe2/cb8590/barra_trees_s4_2020_actnsw_4326_weightings_median/expanded/linear_tifs_lat_32_lon_148_default_percentmethod

echo "Starting elvis_geojsons.pbs for stub $stub"
cd /home/147/cb8590/Projects/shelterbelts/src/shelterbelts/classifications

# Load the conda environment
source /g/data/xe2/cb8590/miniconda/etc/profile.d/conda.sh
conda activate /g/data/xe2/cb8590/miniconda/envs/shelterbelts

# Run the script
# python merge_lidar.py --base_dir $base_dir --suffix _predicted.tif --subdir '' --crs EPSG:3857 --dont_reproject  # Merging the predictions before expanding. Needs 16GB
# python merge_lidar.py --base_dir $base_dir --suffix linear_categories.tif --subdir '' --crs EPSG:3857 --dont_reproject  # Merging the indices
python merge_lidar.py --base_dir $base_dir --suffix shelter_densities.tif --subdir '' --crs EPSG:3857 --dont_reproject  # Merging the indices


# Only needs 4GB memory when merging the 10m tiles in NSW a 30km x 30km area, 
# 8GB for NSW 1m 
# 16GB for ACT 10m
# 64GB for ACT 1m