




def buffer_categories(cover_tif, terrain_tif, savetif=True, plot=True):
    """Reclassify corridors as riparian buffers, ridge buffers, straight lines, and other.
    
    Parameters
    ----------
        cover_tif: Integer tif file generated by cover_categories.py
        terrain_tif: Integer tif file generated by apis.terrain_tiles.py
            
    Returns
    -------
        ds: an xarray with a band 'buffer_categories', where the integers represent the categories defined in 'buffer_category_labels'.

    Downloads
    ---------
        buffer_categories.tif: A tif file of the 'buffer_categories' band in ds, with colours embedded.
        buffer_categories.png: A png file like the tif file, but with a legend as well.
    
    """