import rioxarray as rxr




def buffer_categories(cover_tif, gullies_tif, ridges_tif=None, savetif=True, plot=True):
    """Reclassify corridors as riparian buffers, ridge buffers, straight lines, and other.
    
    Parameters
    ----------
        cover_tif: Integer tif file generated by cover_categories.py
        gullies_tif: Boolean tif file generated by either hydrolines.py or catchments.py
        ridges_tif: Boolean tif file generated by either catchments.py

    Returns
    -------
        ds: an xarray with a band 'buffer_categories', where the integers represent the categories defined in 'buffer_category_labels'.

    Downloads
    ---------
        buffer_categories.tif: A tif file of the 'buffer_categories' band in ds, with colours embedded.
        buffer_categories.png: A png file like the tif file, but with a legend as well.
    
    """


cover_tif = "../../../outdir/g2_26729_cover_categories.tif"

da_cover = rxr.open_rasterio(cover_tif)

da_cover.close()
