
import os
import argparse

import xarray as xr
import rioxarray as rxr

from shelterbelts.apis.worldcover import tif_categorical, visualise_categories
from shelterbelts.apis.worldcover import worldcover_cmap, worldcover_labels
from shelterbelts.indices.tree_categories import tree_categories_cmap, tree_categories_labels


cover_categories_labels = tree_categories_labels | worldcover_labels
cover_categories_cmap = tree_categories_cmap | worldcover_cmap
inverted_labels = {v: k for k, v in cover_categories_labels.items()}


def cover_categories(tree_data, worldcover_data, outdir='.', stub='TEST', savetif=True, plot=True):
    """Overlay WorldCover land use onto the tree categories.

    Parameters
    ----------
    tree_data : str, xarray.Dataset, or xarray.DataArray
        File path to integer tif generated by tree_categories.py, or a Dataset/DataArray
        containing the 'tree_categories' band.
    worldcover_data : str or xarray.DataArray
        File path to integer tif generated by apis.worldcover.py, or a DataArray.
    outdir : str, optional
        Output directory for saving results.
    stub : str, optional
        Prefix for output filenames.
    savetif : bool, optional
        Whether to save the results as a GeoTIFF.
    plot : bool, optional
        Whether to generate a PNG visualisation.

    Returns
    -------
    xarray.Dataset
        Dataset containing 'cover_categories' band, where the integers represent the categories
        defined in 'cover_categories_labels'.

    Notes
    -------
    When savetif=True, it outputs a GeoTIFF file with embedded color map:
    {stub}_cover_categories.tif

    When plot=True, it outputs a PNG visualisation with legend:
    {stub}_cover_categories.png

    Examples
    --------
    Using file paths as input:

    >>> from shelterbelts.utils.filepaths import get_filename
    >>> tree_file = get_filename('g2_26729_tree_categories.tif')
    >>> worldcover_file = get_filename('g2_26729_worldcover.tif')
    >>> ds_cover = cover_categories(tree_file, worldcover_file, outdir='/tmp', plot=False, savetif=False)
    >>> 'cover_categories' in set(ds_cover.data_vars)
    True

    Using datasets as input:

    >>> import rioxarray as rxr
    >>> da_tree = rxr.open_rasterio(tree_file).squeeze('band').drop_vars('band')
    >>> da_worldcover = rxr.open_rasterio(worldcover_file).squeeze('band').drop_vars('band')
    >>> ds_cover = cover_categories(da_tree, da_worldcover, outdir='/tmp', plot=False, savetif=False)
    >>> set(ds_cover.coords) == {'x', 'y', 'spatial_ref'}
    True

    Visualising the cover categories:

    .. plot::

        from shelterbelts.indices.cover_categories import cover_categories, cover_categories_cmap, cover_categories_labels
        from shelterbelts.utils.filepaths import get_filename
        from shelterbelts.utils.visualisation import visualise_categories

        tree_file = get_filename('g2_26729_tree_categories.tif')
        worldcover_file = get_filename('g2_26729_worldcover.tif')

        ds_cover = cover_categories(tree_file, worldcover_file, outdir='/tmp', plot=False, savetif=False)
        visualise_categories(
            ds_cover['cover_categories'],
            colormap=cover_categories_cmap, labels=cover_categories_labels,
            title="Cover Categories"
        )

    """
    if isinstance(tree_data, str):
        da_tree = rxr.open_rasterio(tree_data).squeeze('band').drop_vars('band')
    elif isinstance(tree_data, xr.Dataset):
        da_tree = tree_data['tree_categories']
    else:
        da_tree = tree_data

    if isinstance(worldcover_data, str):
        da_worldcover = rxr.open_rasterio(worldcover_data).squeeze('band').drop_vars('band')
    else:
        da_worldcover = worldcover_data

    da_worldcover2 = da_worldcover.rio.reproject_match(da_tree)

    # Keep tree pixels; label everything else with its WorldCover class
    da_override_trees = xr.where((da_tree >= 10) & (da_tree < 20), da_tree, da_worldcover2)

    # Reassign pixels labelled by worldcover as tree but by the tree tif as not tree, into grassland
    # I'm assuming that the tree tif is more accurate than the worldcover tif in terms of classifying tree vs no tree
    da = xr.where((da_override_trees == inverted_labels['Tree cover']), inverted_labels['Grassland'], da_override_trees)

    # Re-override the water and urban areas with worldcover, because the lidar doesn't seem to be accurate in these categories.
    da = xr.where(da_worldcover2 == inverted_labels['Permanent water bodies'], inverted_labels['Permanent water bodies'], da)
    da = xr.where(da_worldcover2 == inverted_labels['Built-up'], inverted_labels['Built-up'], da)

    ds = da.to_dataset(name='cover_categories')

    # Reassign the crs (unfortunately the xr.where removes the crs from earlier)
    ds.rio.write_crs(da_tree.rio.crs, inplace=True)

    if savetif:
        filename = os.path.join(outdir,f"{stub}_cover_categories.tif")
        tif_categorical(ds['cover_categories'], filename, cover_categories_cmap)

    if plot:
        filename_png = os.path.join(outdir, f"{stub}_cover_categories.png")
        visualise_categories(ds['cover_categories'], filename_png, cover_categories_cmap, cover_categories_labels, "Cover Categories")

    return ds


def parse_arguments():
    """Parse command line arguments with default values."""
    parser = argparse.ArgumentParser()

    parser.add_argument('tree_data', help='Integer tif file generated by tree_categories.py')
    parser.add_argument('worldcover_data', help='Integer tif file generated by apis.worldcover.py')
    parser.add_argument('--outdir', default='.', help='Output directory for saving results (default: current directory)')
    parser.add_argument('--stub', default='TEST', help='Prefix for output filenames (default: TEST)')
    parser.add_argument('--no-savetif', dest='savetif', action="store_false", default=True, help="Disable saving GeoTIFF output (default: enabled)")
    parser.add_argument('--no-plot', dest='plot', action="store_false", default=True, help="Disable PNG visualisation (default: enabled)")

    return parser

# -

if __name__ == '__main__':
    parser = parse_arguments()
    args = parser.parse_args()

    ds = cover_categories(
        args.tree_data,
        args.worldcover_data,
        args.outdir,
        args.stub,
        savetif=args.savetif,
        plot=args.plot
    )
