import xarray as xr
import rioxarray as rxr


# !ls

category_tif = "../../../outdir/TEST_categorised.tif"
height_tif = "../../../outdir/TEST_canopy_height.tif"
wind_ds = "../../../outdir/TEST_barra_daily.nc"

da_categories = rxr.open_rasterio(category_tif).squeeze('band').drop_vars('band')

da_heights = rxr.open_rasterio(height_tif).squeeze('band').drop_vars('band')

ds_wind = xr.load_dataset("../../../outdir/TEST_barra_daily.nc")

ds_wind.sizes['latitude'] >= 1 and ds_wind.sizes['longitude'] >= 1


def shelter_categories(category_tif, height_tif=None, wind_ds=None, wind_method='MOST_COMMON', wind_threshold=15, distance_threshold=20, density_threshold=10, savetif=True, plot=True):
    """Define sheltered and unsheltered pixels
    
    Parameters
    ----------
        category_tif: Integer tif file generated by tree_categories.py
        height_tif: Integer tif file generated by apis.canopy_height.py
            - If not provided, then sheltered/unsheltered is defined by distance in pixels rather than tree heights
        wind_ds: NetCDF with eastward and westward wind speed generated by barra_daily.py
            - If not provided, then sheltered/unsheltered is defined by nearby tree density rather than distance from trees
        wind_method: Either 'MOST_COMMON', 'MAX', or 'ALL'
            - MAX refers to the maximum wind speed
            - MOST_COMMON refers to the most common wind direction above the wind_threshold
            - ALL refers to any direction where the winds exceed the wind_threshold
        wind_threshold: Integer in km/hr
        distance_threshold: The distance from trees that counts as sheltered.
            - Units are either 'tree heights' or 'number of pixels', depending on if a height_tif is provided
        density_threshold: The percentage tree cover within the distance_threshold that counts as sheltered
            - Only applies if the wind_ds is not provided.
            
    Returns
    -------
        ds: an xarray with a band 'shelter_categories', where the integers represent the categories defined in 'shelter_category_labels'.

    Downloads
    ---------
        shelter_categories.tif: A tif file of the 'shelter_categories' band in ds, with colours embedded.
        shelter_categories.png: A png file like the tif file, but with a legend as well.
    
    """
