# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.17.3
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Shelter Categories Demo

# %%
import rioxarray as rxr

from shelterbelts.utils.filepaths import get_filename
from shelterbelts.utils.visualisation import visualise_categories_sidebyside, visualise_categories
from shelterbelts.indices.shelter_categories import shelter_categories
from shelterbelts.indices.shelter_categories import shelter_categories_cmap, shelter_categories_labels

# Example data
tree_categories_file = get_filename('g2_26729_tree_categories.tif')
wind_file = get_filename('g2_26729_barra_daily.nc')
height_file = get_filename('g2_26729_chm_res10_filled.tif')

# %%
# Load the tree categories generated by demo_tree_categories.py
da_tree_categories = rxr.open_rasterio(tree_categories_file).isel(band=0).drop_vars('band')
ds_tree_categories = da_tree_categories.to_dataset(name='tree_categories')


# %% [markdown]
# ## Default Parameters
# The default location is a ~2km x 2km region near Milgadara, NSW, Australia. 

# %%
ds_default = shelter_categories(ds_tree_categories)
visualise_categories(
    ds_default['shelter_categories'],
    colormap=shelter_categories_cmap,
    labels=shelter_categories_labels
)

# %% [markdown]
# ## Changing the density_threshold
#
# The `density_threshold` parameter sets the minimum percentage tree cover (within a radius) that counts as sheltered.

# %%
ds1 = shelter_categories(ds_tree_categories, stub='density3', density_threshold=3)
ds2 = shelter_categories(ds_tree_categories, stub='density10', density_threshold=10)
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="density_threshold=3%", title2="density_threshold=10%"
)

# %% [markdown]
# ## Changing the wind_method
#
# - **MOST_COMMON**: Only downwind shelter using the most common wind direction
# - **WINDWARD**: Both downwind (full distance) and upwind (half distance) shelter
# - **HAPPENED**: Shelter from any direction where winds exceeded the threshold
# - **ANY**: Shelter from all 8 compass directions regardless of wind

# %%
ds1 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_MOST_COMMON', wind_method='MOST_COMMON')
ds2 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_WINDWARD', wind_method='WINDWARD')
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="wind_method=MOST_COMMON", title2="wind_method=WINDWARD"
)

# %%
ds1 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_HAPPENED', wind_method='HAPPENED', wind_threshold=28)
ds2 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_ANY', wind_method='ANY')
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="wind_method=HAPPENED", title2="wind_method=ANY"
)

# %% [markdown]
# ## Changing the distance_threshold
#
# The `distance_threshold` parameter defines how far from trees a pixel is still considered sheltered.
# Units are either pixels (without height data) or tree heights (with height data).

# %%
ds1 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='distance10', distance_threshold=10)
ds2 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='distance30', distance_threshold=30)
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="distance_threshold=10 pixels", title2="distance_threshold=30 pixels"
)

# %% [markdown]
# ### Providing Tree Heights
# If you provide a height tif then the distance_threshold represents the number of tree_heights, rather than the number of 10m pixels downwind from each tree.

# %%
# Example height tif (Canopy Height Model)
chm = rxr.open_rasterio(height_file).isel(band=0).drop_vars('band')
p = chm.plot()
p.axes.set_title('Canopy Height Model')
p.axes.axis('off');

# %%
# This comparison shows that some taller trees provide more shelter than the default, 
# whereas some shorter trees (like in the centre) provide less shelter than the default.
ds1 = shelter_categories(ds_tree_categories, wind_data=wind_file, wind_method='MOST_COMMON', stub='default')  # distance threshold represents the number of pixels (10m each)
ds2 = shelter_categories(ds_tree_categories, wind_data=wind_file, wind_method='MOST_COMMON', height_tif=height_file, stub='heights_provided', distance_threshold=15)  # distance_threshold represents the number of "tree_heights"
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="default", title2="Height tif"
)

# %% [markdown]
# ## Changing the wind_threshold
#
# The `wind_threshold` parameter sets the wind speed (km/h) used to determine dominant wind direction.
# Only used when `wind_data` is provided.

# %%
ds1 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_threshold10', wind_threshold=10)
ds2 = shelter_categories(ds_tree_categories, wind_data=wind_file, stub='wind_threshold30', wind_threshold=30)
visualise_categories_sidebyside(
    ds1['shelter_categories'], ds2['shelter_categories'],
    colormap=shelter_categories_cmap, labels=shelter_categories_labels,
    title1="wind_threshold=10 km/h", title2="wind_threshold=30 km/h"
)

# %% [markdown]
# ## Command Line Interface
# You can also use the function from the command line with the same defaults and parameters.

# %%
from shelterbelts.utils.filepaths import setup_repo_path
setup_repo_path()

# %%
# !python shelterbelts/indices/shelter_categories.py --help  # Could use -m to avoid needing the setup_repo_path (but we need this anyway for the file removing later)

# %%
# %%time
# !python shelterbelts/indices/shelter_categories.py {tree_categories_file} --stub command_line_defaults --outdir ../notebooks/indices

# %%
# !python shelterbelts/indices/shelter_categories.py {tree_categories_file} --wind_data {wind_file} --height_tif {height_file} --wind_method MOST_COMMON --distance_threshold 10 --stub command_line --outdir ../notebooks/indices

# %% [markdown]
# ### Cleanup
# Remove the output files created by this notebook

# %%
# !rm ../notebooks/indices/*.tif
# !rm ../notebooks/indices/*.png
# !rm ../notebooks/indices/*.xml  # These get generated if you load the tifs in QGIS
