import os
import pickle
import argparse

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

from shelterbelts.classifications.neural_network import (
    my_train_test_split,
    inputs_outputs_split,
    class_accuracies_overall,
)


def random_forest(training_file, outdir=".", stub="TEST", output_column='tree_cover', drop_columns=['x', 'y', 'tile_id'], n_estimators=100, min_samples_split=10, random_state=1, stratification_columns=['tree_cover'], train_frac=0.7, limit=None):
    """
    Train and evaluate a random forest classifier for tree vs non-tree pixels.

    Parameters
    ----------
    training_file : str
        Path to a .csv or .feather training dataset produced by
        :func:`shelterbelts.classifications.merge_inputs_outputs.merge_inputs_outputs`.
    outdir : str, optional
        Output directory for saving results.
    stub : str, optional
        Prefix for every output filename.
    output_column : str, optional
        Name of the binary label column.
    drop_columns : list of str, optional
        Non-feature columns to exclude from training.
    n_estimators : int, optional
        Number of trees in the forest.
    min_samples_split : int, optional
        Minimum samples required to split an internal node.
    random_state : int, optional
        Seed for the train/test split and the forest.
    stratification_columns : list of str, optional
        Columns to stratify the train/test split on.
    train_frac : float, optional
        Training fraction after stratified balancing.
    limit : int, optional
        Randomly subsample rows before training. If None, use all rows.

    Returns
    -------
    pandas.DataFrame
        Per-class precision/recall/f1/accuracy on the held-out test set.

    Notes
    -----
    Writes to outdir:

    - {stub}_random_forest.pkl — the pickled RandomForestClassifier
    - scaler_{stub}.pkl — matching StandardScaler (kept for API symmetry
      with the NN; the trees don't strictly need scaled inputs)
    - {stub}_metrics.csv — per-class metrics
    """
    if training_file.endswith('.feather'):
        df = pd.read_feather(training_file)
    else:
        df = pd.read_csv(training_file)

    if limit:
        df = df.sample(limit, random_state=random_state)

    df_train, df_test = my_train_test_split(df, stratification_columns, train_frac, random_state)

    non_input_columns = [output_column] + drop_columns
    X_train, X_test, y_train, y_test, scaler = inputs_outputs_split(df_train, df_test, outdir, stub, non_input_columns, output_column)

    model = RandomForestClassifier(n_estimators=n_estimators, min_samples_split=min_samples_split, random_state=random_state)
    model.fit(X_train, y_train)

    filename = os.path.join(outdir, f'{stub}_random_forest.pkl')
    with open(filename, "wb") as f:
        pickle.dump(model, f)
    print(f"Saved: {filename}")

    df_accuracy = class_accuracies_overall(df_test, model, scaler, outdir, stub, non_input_columns, output_column)
    return df_accuracy


def parse_arguments():
    """Parse command line arguments with default values."""
    parser = argparse.ArgumentParser()
    parser.add_argument('training_file', help='Either a .feather or .csv file, generated by merge_inputs_outputs')
    parser.add_argument('--outdir', default='.', help='Directory of the outputs (default: current directory)')
    parser.add_argument('--stub', default='TEST_RF', help='Prefix of the outputs (default: TEST_RF)')
    parser.add_argument('--output_column', default='tree_cover', help='Column with the output data (default: tree_cover)')
    parser.add_argument('--drop_columns', nargs='+', default=['x', 'y', 'tile_id'], help='Columns to drop (default: x y tile_id)')
    parser.add_argument('--n_estimators', type=int, default=100, help='Number of trees (default: 100)')
    parser.add_argument('--min_samples_split', type=int, default=10, help='Minimum samples to split (default: 10)')
    parser.add_argument('--random_state', type=int, default=1, help='Random seed (default: 1)')
    parser.add_argument('--stratification_columns', nargs='+', default=['tree_cover'], help='Columns to stratify on (default: tree_cover)')
    parser.add_argument('--train_frac', type=float, default=0.7, help='Training sample fraction (default: 0.7)')
    parser.add_argument('--limit', type=int, default=None, help='Number of rows to use (default: all)')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_arguments()
    random_forest(
        args.training_file,
        outdir=args.outdir,
        stub=args.stub,
        output_column=args.output_column,
        drop_columns=args.drop_columns,
        n_estimators=args.n_estimators,
        min_samples_split=args.min_samples_split,
        random_state=args.random_state,
        stratification_columns=args.stratification_columns,
        train_frac=args.train_frac,
        limit=args.limit,
    )
