import argparse
import os
import pickle
import sys
import traceback

import geopandas as gpd
import rioxarray as rxr
import odc.stac
import pystac_client


STAC_URL = 'https://explorer.dea.ga.gov.au/stac'
PRODUCTS = ['ga_s2am_ard_3', 'ga_s2bm_ard_3', 'ga_s2cm_ard_3']
BANDS = [
    'nbart_blue', 'nbart_green', 'nbart_red',
    'nbart_red_edge_1', 'nbart_red_edge_2', 'nbart_red_edge_3',
    'nbart_nir_1', 'nbart_nir_2',
    'nbart_swir_2', 'nbart_swir_3',
]


def search_stac(bbox, start_date, end_date, cloud_cover=10):
    """Search the DEA STAC catalogue and return matching items."""
    catalog = pystac_client.Client.open(STAC_URL)
    odc.stac.configure_rio(cloud_defaults=True, aws={'aws_unsigned': True})
    results = catalog.search(
        bbox=bbox,
        collections=PRODUCTS,
        datetime=f"{start_date}/{end_date}",
        filter=f"eo:cloud_cover < {cloud_cover}",
    )
    return list(results.items())


def load_and_process_data(items, bbox, crs='utm'):
    """Load all 10 bands from a list of STAC items via odc.stac."""
    ds = odc.stac.load(
        items,
        bands=BANDS,
        crs=crs,
        resolution=10,
        groupby='solar_day',
        bbox=bbox,
        chunks={'time': 1, 'x': 1024, 'y': 1024},
    )
    return ds


def download_ds2(tif, start_date="2020-01-01", end_date="2021-01-01", outdir=".", save=True):
    """Download Sentinel imagery matching the bounding box of an existing tif file."""
    da = rxr.open_rasterio(tif).isel(band=0).drop_vars('band')
    da_4326 = da.rio.reproject('EPSG:4326')
    bbox = da_4326.rio.bounds()
    stub = tif.split('/')[-1].split('.')[0]
    return download_ds2_bbox(bbox, start_date, end_date, outdir, stub, save)


def download_ds2_bbox(bbox, start_date="2020-01-01", end_date="2021-01-01", outdir=".", stub="TEST", save=True):
    """
    Download a Sentinel-2 surface reflectance stack for a bounding box and date range.

    Uses the public DEA STAC catalogue (no NCI/datacube access required). Applies a
    10 % cloud-cover filter and downloads all 10 surface-reflectance bands. Data are
    returned as a lazy Dask-backed Dataset; call ``.compute()`` on a slice before
    plotting.

    Parameters
    ----------
    bbox : tuple of float
        (minx, miny, maxx, maxy) in EPSG:4326 (the STAC API always expects geographic
        coordinates, unlike the NCI datacube path which accepts an ``input_crs``).
    start_date, end_date : str, optional
        ISO date strings bounding the search window.
    outdir : str, optional
        Directory for the saved pickle file.
    stub : str, optional
        Filename prefix; the file is written to ``{outdir}/{stub}_ds2_{year}.pkl``.
    save : bool, optional
        Whether to pickle the Dataset to disk.

    Returns
    -------
    xarray.Dataset
        Ten-band Sentinel-2 stack with dims ``(time, y, x)`` in the local UTM zone.

    Notes
    -----
    Cloud filtering uses the ``eo:cloud_cover`` STAC field (scene-level metadata),
    which is coarser than the pixel-level ``s2cloudless`` mask used by the NCI
    ``load_ard`` path.  The output CRS is the auto-detected UTM zone for the area,
    rather than the fixed EPSG:3857 used on NCI.
    """
    items = search_stac(bbox, start_date, end_date)
    ds = load_and_process_data(items, bbox)

    if save:
        year = start_date[:4]
        filename = os.path.join(outdir, f'{stub}_ds2_{year}.pkl')
        with open(filename, 'wb') as handle:
            pickle.dump(ds, handle, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"Saved {filename}", flush=True)

    return ds


def run_download_gdf(gdf, outdir, start_date='2020-01-01', end_date='2021-01-01'):
    """Run :func:`download_ds2_bbox` on every row in the GeoDataFrame."""
    for _, row in gdf.iterrows():
        filename = row['filename']
        if 'start_date' in gdf.columns and 'end_date' in gdf.columns:
            start_date = row['start_date']
            end_date = row['end_date']
        stub = filename.split('.')[0] + '_' + start_date[:4]
        bounds = row['geometry'].bounds

        try:
            print(f"Downloading: {stub}_{start_date}_{end_date}", flush=True)
            download_ds2_bbox(bounds, start_date, end_date, outdir, stub)
        except Exception:
            print(f"Error downloading: {stub}_{start_date}_{end_date}:", flush=True)
            traceback.print_exc(file=sys.stdout)


def parse_arguments():
    """Parse command line arguments with default values."""
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("gpkg", type=str, help="A gpkg with: (filename, [start_date], [end_date], geometry), generated by bounding_boxes.py. The start_date and end_date columns override the CLI arguments.")
    parser.add_argument("outdir", type=str, help="Output directory for the pickle files")
    parser.add_argument("--limit", type=int, default=None, help="Number of files to process")
    parser.add_argument("--start_date", type=str, default='2020-01-01', help="Starting date to download sentinel imagery (default='2020-01-01')")
    parser.add_argument("--end_date", type=str, default='2021-01-01', help="Ending date to download sentinel imagery (default='2021-01-01')")
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_arguments()
    gdf = gpd.read_file(args.gpkg)
    if args.limit is not None:
        gdf = gdf[:args.limit]
    run_download_gdf(gdf, args.outdir, args.start_date, args.end_date)
