# %%
# Create a gpkg of 4km tiles around areas with at least one potential modified pasture or cropping pixel (250m)

# %%
import rioxarray as rxr
import geopandas as gpd
from rasterio.features import shapes
from shapely.geometry import shape

# %%
# Downloaded from here: https://www.agriculture.gov.au/abares/aclump/land-use/land-use-of-australia-2010-11-to-2020-21#downloads
# The filename is: "Land use of Australia 2020–21 agricultural commodities probability grids - raster package (GeoTIFF and supporting files) (ZIP 246 MB)"
grazing_modified_pastures = "/home/christopher-bradley/Documents/PHD/data/Outlines/NLUM_v7_250_AgProbabilitySurfaces_2020_21_geo_package_20241128/NLUM_v7_probSurf_2021_320_3_GRAZ_NOTIMBSP.tif"
# cropping_winter_cereals = "/home/christopher-bradley/Documents/PHD/data/Outlines/NLUM_v7_250_AgProbabilitySurfaces_2020_21_geo_package_20241128/NLUM_v7_probSurf_2021_331_5_W_CER.tif"

# Generated by demo_koppen_preparation.py
koppen_cleaned = '/home/christopher-bradley/repos/shelterbelts/models/Koppen_Australia_cleaned2.gpkg'

# Taken from one of the .nc files, e.g. https://thredds.nci.org.au/thredds/fileServer/ob53/output/reanalysis/AUST-04/BOM/ERA5/historical/hres/BARRA-C2/v1/day/uas/latest/uas_AUST-04_ERA5_historical_hres_BOM_BARRA-C2_v1_day_202001-202001.nc
gdf_bboxs = gpd.read_file("/home/christopher-bradley/Documents/PHD/data/Outlines/barra_bboxs_aus.gpkg")

# Generated by demo_year_parsing.py
gdf_footprints_years = gpd.read_file("tiff_footprints_years.gpkg")

# Generated by bounding_boxes.py on the folder of provided tifs
gdf_footprints = gpd.read_file("/home/christopher-bradley/Documents/PHD/data/Outlines/cb8590_Nick_Aus_treecover_10m_footprints.gpkg")


# %%
# Create a copy of barra_bboxs in just the pixels where grazing_modified_pastures is not no data.
da_graz = rxr.open_rasterio(grazing_modified_pastures, masked=True).isel(band=0).squeeze()
valid_mask = (~da_graz.isnull()).astype('uint8').values
valid_mask

# %%
gdf_bboxs = gdf_bboxs.to_crs(da_graz.rio.crs)
gdf_bboxs

# %%
# Fast way of doing a spatial intersection (Claud generated and seems to work nicely)
import numpy as np
import time
from rasterio.transform import rowcol

transform = da_graz.rio.transform()
nrows, ncols = valid_mask.shape

# Pad with a zero border so the integral formula never needs boundary checks
integral = np.zeros((nrows + 1, ncols + 1), dtype=np.int32)
integral[1:, 1:] = valid_mask.astype(np.int32).cumsum(axis=0).cumsum(axis=1)

def bboxs_with_valid_pixels(gdf, integral, transform, nrows, ncols):
    """Return boolean mask: True where bbox overlaps at least one valid pixel."""
    bounds = gdf.bounds  # minx, miny, maxx, maxy
    # Top-left corner of bbox → smallest row/col; bottom-right → largest row/col
    r0, c0 = rowcol(transform, bounds.minx.values, bounds.maxy.values)
    r1, c1 = rowcol(transform, bounds.maxx.values, bounds.miny.values)
    r0 = np.clip(r0, 0, nrows - 1)
    r1 = np.clip(r1, 0, nrows - 1)
    c0 = np.clip(c0, 0, ncols - 1)
    c1 = np.clip(c1, 0, ncols - 1)
    # Inclusion-exclusion on the padded integral image
    sums = (integral[r1 + 1, c1 + 1]
            - integral[r0,     c1 + 1]
            - integral[r1 + 1, c0    ]
            + integral[r0,     c0    ])
    return sums > 0

# %%
mask_full = bboxs_with_valid_pixels(gdf_bboxs, integral, transform, nrows, ncols)
gdf_filtered = gdf_bboxs[mask_full].reset_index(drop=True)
print(f"kept {len(gdf_filtered):,} / {len(gdf_bboxs):,} bboxes")
gdf_filtered.to_file('barra_bboxs_grazing.gpkg')
gdf_filtered

# %%
gdf_koppen = gpd.read_file(koppen_cleaned)
gdf_koppen

# %%
# Remove tiles that intersect the BWh (hot desert) Koppen zone, since different farming practices (e.g. water ponding) are probably more appropriate than shelterbelts.
bwh = gdf_koppen[gdf_koppen['Name'] == 'BWh'][['geometry']].to_crs(gdf_filtered.crs)
joined = gpd.sjoin(gdf_filtered, bwh, how='left', predicate='intersects')
gdf_no_bwh = gdf_filtered[joined['index_right'].isna()].reset_index(drop=True)
print(f"Removed {len(gdf_filtered) - len(gdf_no_bwh):,} BWh tiles  |  kept {len(gdf_no_bwh):,}")
gdf_no_bwh.to_file('barra_bboxs_grazing_no_bwh.gpkg')
gdf_no_bwh

# %%
# Merge footprints with year metadata, filter to large recent tifs outside of the desert
gdf_merged = gdf_footprints.merge(gdf_footprints_years[['filename', 'year']], on='filename', how='inner')
gdf_merged = gdf_merged[(gdf_merged['year'] > 2016) & (gdf_merged['bad_tif'] == False)].reset_index(drop=True)
print(f"After year/bad_tif filter: {len(gdf_merged):,}")

tiles = gdf_no_bwh[['geometry']].to_crs(gdf_merged.crs)
joined = gpd.sjoin(gdf_merged, tiles, how='inner', predicate='intersects')
gdf_footprints_final = gdf_merged.loc[joined.index.unique()].reset_index(drop=True)
print(f"After tile filter: {len(gdf_footprints_final):,}")
gdf_footprints_final.to_file('footprints_filtered.gpkg')
gdf_footprints_final

# %%
