#!/usr/bin/env python
"""
Summarise tree/cover categories generated by tif_value_counts.py across methods.

Usage:
    # Tree categories (11-19) across the 6 methods in the global folder:
    python category_area_summary.py \
        --input_dir outdir/tif_value_counts/global \
        --suffix merged_shelter_categories.csv \
        --value_range 11-19 \
        --output_csv outdir/tif_value_counts/global/summary_tree_categories.csv

"""

import os
import glob
import argparse

import pandas as pd

from shelterbelts.indices.all_indices import GEE_legend

ALL_ZONE = "ALL"
PIXEL_SIZE_M = 10  # raster resolution, for pixel-count -> hectare conversion


def parse_value_range(value_range):
    """Parse '11-19' or '30,31,40-49' into a sorted list of ints."""
    values = set()
    for part in value_range.split(","):
        part = part.strip()
        if "-" in part:
            lo, hi = part.split("-")
            values.update(range(int(lo), int(hi) + 1))
        else:
            values.add(int(part))
    return sorted(values)


def find_methods(input_dir, suffix):
    """Glob `input_dir` for files ending in `suffix`, return {method: path}."""
    paths = sorted(glob.glob(os.path.join(input_dir, f"*{suffix}")))
    methods = {}
    for path in paths:
        filename = os.path.basename(path)
        method = filename[: -len(suffix)].rstrip("_")
        methods[method] = path
    return methods


UNIT_COLUMNS = {"hectares": "count", "pixels": "count", "percentage": "percent"}


def category_area_summary(input_dir, suffix, value_range, zone=ALL_ZONE,
                           methods=None, legend=GEE_legend,
                           pixel_size_m=PIXEL_SIZE_M, units="hectares"):
    """Build a category-x-method table from matching value-count CSVs.

    methods : optional {method_name: csv_path} dict. Defaults to every file
        in `input_dir` ending with `suffix` (see find_methods()).
    units : 'hectares' (count converted via pixel_size_m, rounded to the
        nearest whole number), 'pixels' (raw count), or 'percentage' (the
        source CSV's 'percent' column, i.e. % of valid pixels in the zone,
        formatted as e.g. '13.45%').
    Returns a DataFrame indexed by category label, one column per method.
    """
    if units not in UNIT_COLUMNS:
        raise ValueError(f"units must be one of {list(UNIT_COLUMNS)}, got {units!r}")
    if methods is None:
        methods = find_methods(input_dir, suffix)
    if not methods:
        raise SystemExit(f"No '*{suffix}' files found in {input_dir}")

    values = parse_value_range(value_range)
    pixel_area_ha = (pixel_size_m ** 2) / 10_000
    metric_col = UNIT_COLUMNS[units]

    method_values = {}
    present_values = set()
    for method, path in methods.items():
        df = pd.read_csv(path)
        df = df[(df["zone"] == zone) & (df["value"].isin(values))]
        metric = df.set_index("value")[metric_col].to_dict()
        if units == "hectares":
            metric = {v: c * pixel_area_ha for v, c in metric.items()}
        method_values[method] = metric
        present_values.update(metric.keys())

    # Only keep categories that actually have pixels in at least one method,
    row_values = [v for v in values if v in present_values]
    row_labels = [legend.get(v, str(v)) for v in row_values]

    table = pd.DataFrame(
        {method: [method_values[method].get(v, 0.0) for v in row_values]
         for method in methods},
        index=row_labels,
    )
    table.index.name = "category"

    if units in ("hectares", "pixels"):
        table = table.round(0).astype(int)
    else:
        table = table.round(2).map(lambda x: f"{x:.2f}%")
    return table


def run(input_dir, suffix, value_range, zone=ALL_ZONE, output_csv=None,
        units="hectares"):
    table = category_area_summary(input_dir, suffix, value_range, zone=zone,
                                   units=units)
    print(table.to_string(), flush=True)

    if output_csv:
        os.makedirs(os.path.dirname(os.path.abspath(output_csv)), exist_ok=True)
        table.to_csv(output_csv)
        print(f"Saved: {output_csv}", flush=True)
    return table


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Summarise category areas (hectares) across methods, "
                    "from tif_value_counts.py output CSVs.")
    parser.add_argument("--input_dir", required=True,
                        help="Folder containing the per-method CSVs.")
    parser.add_argument("--suffix", required=True,
                        help="Common filename suffix identifying the CSVs to "
                            "compare, e.g. merged_shelter_categories.csv")
    parser.add_argument("--value_range", required=True,
                        help="Category values to include, e.g. '11-19' or "
                            "'30,31,40-49'.")
    parser.add_argument("--zone", default=ALL_ZONE,
                        help="Zone to read from each CSV (default: ALL, the "
                            "whole-dataset total).")
    parser.add_argument("--units", default="hectares",
                        choices=list(UNIT_COLUMNS),
                        help="Units for the table cells (default: hectares).")
    parser.add_argument("--output_csv", default=None,
                        help="Where to write the summary table.")
    args = parser.parse_args()

    run(args.input_dir, args.suffix, args.value_range, zone=args.zone,
        output_csv=args.output_csv, units=args.units)
