#!/usr/bin/env python
"""
Summarise tree/cover categories generated by tif_value_counts.py across methods.

Usage:
    # Tree categories (11-19) across the 6 methods in the global folder:
    python category_area_summary.py \
        --input_dir outdir/tif_value_counts/global \
        --suffix merged_shelter_categories.csv \
        --value_range 11-19 \
        --output_csv outdir/tif_value_counts/global/summary_tree_categories.csv

Code generated by Claude, verified by comparing plots with the csvs containing the original data.
"""

import os
import glob
import argparse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from shelterbelts.indices.all_indices import GEE_legend
from shelterbelts.indices.shelter_categories import (
    shelter_categories_cmap, _blend_rgb, _tree_blend_amount,
)
from shelterbelts.indices.patch_metrics import linear_categories_cmap

ALL_ZONE = "ALL"
PIXEL_SIZE_M = 10  # raster resolution, for pixel-count -> hectare conversion

# Mirrors shelterPalette in google_earth_engine/shelterbelts_aus_exportable.js
# (RGB 0-255) so bar colours match the GEE map colours for the same category.
SHELTER_PALETTE = {
    0:   (255, 255, 255),
    10:  (0, 100, 0),
    11:  (122, 82, 0),
    12:  (8, 79, 0),
    13:  (14, 138, 0),
    14:  (22, 212, 0),
    15:  (29, 153, 105),
    16:  (127, 168, 57),
    17:  (129, 146, 124),
    18:  (190, 160, 60),
    19:  (165, 195, 45),
    20:  (255, 187, 34),
    30:  (255, 255, 76),
    31:  (203, 219, 115),
    32:  (255, 255, 76),
    40:  (240, 150, 255),
    41:  (146, 104, 143),
    42:  (240, 150, 255),
    50:  (250, 0, 0),
    60:  (180, 180, 180),
    70:  (240, 240, 240),
    80:  (0, 100, 200),
    90:  (0, 150, 160),
    95:  (0, 207, 117),
    100: (250, 230, 160),
}

# shelter_categories.py deliberately reuses the grassland colours for sheltered
# cropland too (30-39/40-49 look identical in the tif output, by design) - but
# that makes grassland-vs-cropland charts hard to tell apart, so for charts
# only, rebuild the same tree-blend using a pink cropland base colour instead.
CROPLAND_BASE = (240, 150, 255)  # matches the cropland colour in SHELTER_PALETTE
CROPLAND_PALETTE = dict(shelter_categories_cmap)
CROPLAND_PALETTE[40] = CROPLAND_BASE
for _digit in range(2, 10):
    CROPLAND_PALETTE[40 + _digit] = _blend_rgb(
        CROPLAND_BASE, linear_categories_cmap[10 + _digit], _tree_blend_amount)


def _lighten(rgb, amount):
    """Blend an (r, g, b) colour towards white by `amount` (0-1) - pastel
    tints that work as a table-cell background with black text."""
    return tuple(round(c + (255 - c) * amount) for c in rgb)


# Pastel version of SHELTER_PALETTE (~65% white blend) for table-cell
# backgrounds, e.g. plot_patch_metrics_table().
LIGHT_SHELTER_PALETTE = {v: _lighten(rgb, 0.65) for v, rgb in SHELTER_PALETTE.items()}


def parse_value_range(value_range):
    """Parse '11-19' or '30,31,40-49' into a sorted list of ints."""
    values = set()
    for part in value_range.split(","):
        part = part.strip()
        if "-" in part:
            lo, hi = part.split("-")
            values.update(range(int(lo), int(hi) + 1))
        else:
            values.add(int(part))
    return sorted(values)


def find_methods(input_dir, suffix):
    """Glob `input_dir` for files ending in `suffix`, return {method: path}."""
    paths = sorted(glob.glob(os.path.join(input_dir, f"*{suffix}")))
    methods = {}
    for path in paths:
        filename = os.path.basename(path)
        method = filename[: -len(suffix)].rstrip("_")
        methods[method] = path
    return methods


UNIT_COLUMNS = {"hectares": "count", "pixels": "count", "percentage": "percent"}


def _numeric_table(input_dir, suffix, value_range, zone, methods, legend,
                    pixel_size_m, units, order_by):
    """Shared loading logic: raw per-method values (unformatted), sorted."""
    if methods is None:
        methods = find_methods(input_dir, suffix)
    if not methods:
        raise SystemExit(f"No '*{suffix}' files found in {input_dir}")

    values = parse_value_range(value_range)
    pixel_area_ha = (pixel_size_m ** 2) / 10_000
    metric_col = UNIT_COLUMNS[units]

    method_values = {}
    present_values = set()
    for method, path in methods.items():
        df = pd.read_csv(path)
        df = df[(df["zone"] == zone) & (df["value"].isin(values))]
        metric = df.set_index("value")[metric_col].to_dict()
        if units == "hectares":
            metric = {v: c * pixel_area_ha for v, c in metric.items()}
        method_values[method] = metric
        present_values.update(metric.keys())

    # Only keep categories that actually have pixels in at least one method,
    row_values = [v for v in values if v in present_values]
    row_labels = [legend.get(v, str(v)) for v in row_values]

    table = pd.DataFrame(
        {method: [method_values[method].get(v, 0.0) for v in row_values]
         for method in methods},
        index=row_labels,
    )
    table.index.name = "category"

    if order_by:
        if order_by in table.columns:
            table = table.sort_values(order_by, ascending=False)
        else:
            print(f"Warning: order_by column '{order_by}' not in "
                  f"{list(table.columns)}; leaving table unsorted", flush=True)
    return table


def category_area_summary(input_dir, suffix, value_range, zone=ALL_ZONE,
                           methods=None, legend=GEE_legend,
                           pixel_size_m=PIXEL_SIZE_M, units="hectares",
                           order_by="default"):
    """Build a category-x-method table from matching value-count CSVs.

    methods : optional {method_name: csv_path} dict. Defaults to every file
        in `input_dir` ending with `suffix` (see find_methods()).
    units : 'hectares' (count converted via pixel_size_m, rounded to the
        nearest whole number), 'pixels' (raw count), or 'percentage' (the
        source CSV's 'percent' column, i.e. % of valid pixels in the zone,
        formatted as e.g. '13.45%').
    order_by : method column to sort rows by, descending (default: 'default').
        Pass '' / None to leave rows in category-value order.
    Returns a DataFrame indexed by category label, one column per method.
    """
    if units not in UNIT_COLUMNS:
        raise ValueError(f"units must be one of {list(UNIT_COLUMNS)}, got {units!r}")

    table = _numeric_table(input_dir, suffix, value_range, zone, methods,
                           legend, pixel_size_m, units, order_by)

    if units in ("hectares", "pixels"):
        table = table.round(0).astype(int)
    else:
        table = table.round(2).map(lambda x: f"{x:.2f}%")
    return table


def _draw_bars_with_error(ax, index, default, err_low, err_high, colors, ylabel,
                          title, value_fontsize=8, rotation=30):
    """Shared renderer for a default-height / less-more-error-bar bar chart."""
    default = np.asarray(default, dtype=float)
    err_high = np.asarray(err_high, dtype=float)
    ax.bar(index, default, color=colors, edgecolor="black", linewidth=0.5,
           yerr=[err_low, err_high], capsize=4, ecolor="black")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.yaxis.set_major_formatter(lambda y, _: f"{y:,.0f}")
    plt.setp(ax.get_xticklabels(), rotation=rotation, ha="right")

    label_pad = default.max() * 0.02
    for x, (val, top) in enumerate(zip(default, default + err_high)):
        ax.text(x, top + label_pad, f"{val:,.0f}", ha="center", va="bottom",
                fontsize=value_fontsize)
    ax.margins(y=0.12)


def plot_category_bars(input_dir, suffix, value_range, zone=ALL_ZONE,
                        methods=None, legend=GEE_legend,
                        pixel_size_m=PIXEL_SIZE_M, order_by="default",
                        category_order=None, palette=SHELTER_PALETTE,
                        title=None, output_png=None, ax=None,
                        value_fontsize=8):
    """Bar chart of hectares by category, coloured per SHELTER_PALETTE.

    Bar height is the 'default' method's hectares; asymmetric error bars
    span the 'less'/'more' methods (whichever is lower/higher), so they
    read as an uncertainty range around the default estimate. Requires
    'default', 'less', and 'more' columns/methods to be present.

    category_order : optional explicit list of category labels (rows), used
        instead of `order_by` sorting — e.g. to keep the same row order
        across several panels of a grid (see plot_category_grid()).
    ax : optional matplotlib Axes to draw into (e.g. one panel of a grid).
        If omitted, a new standalone figure is created (and saved to
        `output_png`, if given).
    """
    hectares = _numeric_table(input_dir, suffix, value_range, zone, methods,
                              legend, pixel_size_m, "hectares",
                              order_by=None if category_order else order_by)
    if category_order is not None:
        hectares = hectares.reindex(category_order).fillna(0.0)
    required = {"default", "less", "more"}
    if not required.issubset(hectares.columns):
        raise ValueError(f"Plotting needs {sorted(required)} columns/methods, "
                         f"got {list(hectares.columns)}")

    values = parse_value_range(value_range)
    # Some codes share a label (e.g. 30/31 both 'Unsheltered Grassland', 31
    # being a legacy code) - keep the first (smallest/canonical) value's colour.
    label_to_value = {}
    for v in values:
        label_to_value.setdefault(legend.get(v, str(v)), v)
    colors = [tuple(c / 255 for c in palette.get(label_to_value.get(cat), (127, 127, 127)))
              for cat in hectares.index]

    default = hectares["default"].astype(float)
    lower = np.minimum(hectares["less"], hectares["more"])
    upper = np.maximum(hectares["less"], hectares["more"])
    err_low = (default - lower).clip(lower=0)
    err_high = (upper - default).clip(lower=0)

    region = "Australia" if zone == ALL_ZONE else zone
    title = title or f"Tree Categories - {region}"

    standalone = ax is None
    if standalone:
        # Widen the figure for long titles so they don't get clipped by the canvas.
        width = max(6, 0.9 * len(default), 0.11 * len(title))
        fig, ax = plt.subplots(figsize=(width, 6))
    else:
        fig = ax.figure

    _draw_bars_with_error(ax, hectares.index, default, err_low, err_high, colors,
                          "Hectares", title, value_fontsize=value_fontsize)

    if standalone:
        fig.tight_layout()
        if output_png:
            os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
            fig.savefig(output_png, dpi=150)
            print(f"Saved: {output_png}", flush=True)
    return fig


def load_metric_table(input_dir, suffix, metric, category_col="category_name",
                      methods=None, order_by="default"):
    """Load a category-x-method table from CSVs with a flat category/metric
    schema (category_col, metric, ...) - e.g. patch_metrics_summary.py output,
    as opposed to the zone/value/count/percent schema used elsewhere in this
    module.

    Returns a DataFrame indexed by category, one column per method.
    """
    if methods is None:
        methods = find_methods(input_dir, suffix)
    if not methods:
        raise SystemExit(f"No '*{suffix}' files found in {input_dir}")

    table = pd.DataFrame({
        method: pd.read_csv(path).set_index(category_col)[metric]
        for method, path in methods.items()
    })
    table.index.name = "category"

    if order_by:
        if order_by in table.columns:
            table = table.sort_values(order_by, ascending=False)
        else:
            print(f"Warning: order_by column '{order_by}' not in "
                  f"{list(table.columns)}; leaving table unsorted", flush=True)
    return table


def plot_metric_bars(input_dir, suffix, metric, ylabel, category_col="category_name",
                     methods=None, legend=GEE_legend, order_by="default",
                     category_order=None, palette=SHELTER_PALETTE, title=None,
                     output_png=None, ax=None, value_fontsize=8):
    """Bar chart of an arbitrary per-category metric (e.g. row_count from
    patch_metrics_summary.py), coloured per SHELTER_PALETTE. Same
    default/less/more error-bar convention as plot_category_bars(), just
    sourced from a flat category/metric CSV instead of a zone/value/count one.
    """
    table = load_metric_table(input_dir, suffix, metric, category_col, methods,
                              order_by=None if category_order else order_by)
    if category_order is not None:
        table = table.reindex(category_order).fillna(0.0)
    required = {"default", "less", "more"}
    if not required.issubset(table.columns):
        raise ValueError(f"Plotting needs {sorted(required)} columns/methods, "
                         f"got {list(table.columns)}")

    label_to_value = {}
    for v, lab in legend.items():
        label_to_value.setdefault(lab, v)
    colors = [tuple(c / 255 for c in palette.get(label_to_value.get(cat), (127, 127, 127)))
              for cat in table.index]

    default = table["default"].astype(float)
    lower = np.minimum(table["less"], table["more"])
    upper = np.maximum(table["less"], table["more"])
    err_low = (default - lower).clip(lower=0)
    err_high = (upper - default).clip(lower=0)

    title = title or ylabel

    standalone = ax is None
    if standalone:
        width = max(6, 0.9 * len(default), 0.11 * len(title))
        fig, ax = plt.subplots(figsize=(width, 6))
    else:
        fig = ax.figure

    _draw_bars_with_error(ax, table.index, default, err_low, err_high, colors,
                          ylabel, title, value_fontsize=value_fontsize)

    if standalone:
        fig.tight_layout()
        if output_png:
            os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
            fig.savefig(output_png, dpi=150)
            print(f"Saved: {output_png}", flush=True)
    return fig


# Patch-metrics summary table (patch_metrics_summary.py output -> a styled
# per-category stats table, not a bar chart).
PATCH_METRICS_COLUMNS = {
    # display column -> (source column, units per pixel-unit, display unit)
    "Median length":    ("ellipse_length_median", PIXEL_SIZE_M, "m"),
    "Median perimeter": ("perimeter_median", PIXEL_SIZE_M, "m"),
    "Median width":     ("ellipse_width_median", PIXEL_SIZE_M, "m"),
    "Median area":      ("area_mean", 0.01, "ha"),  # mean, not median - see patch_metrics_table()
    "Total Length":     ("ellipse_length_sum", PIXEL_SIZE_M / 1000, "km"),
    "Total Perimeter":  ("perimeter_sum", PIXEL_SIZE_M / 1000, "km"),
    "Total Area":       ("area_sum", 0.01, "ha"),
}


def _category_sort_key(category, legend):
    for value, label in legend.items():
        if label == category:
            return value
    return float("inf")


def patch_metrics_table(csv_path, category_col="category_name", legend=GEE_legend):
    """Build the 7-column patch-metrics stats table from one
    patch_metrics_summary.py CSV (e.g. default_percentmethod_...csv).

    'Median area' is actually the per-group *mean* area (area_mean), not the
    median - matching the convention used for these tables so far (median for
    length/perimeter/width, since those are skewed by a few huge patches;
    mean for area, which is closer to a "typical" patch footprint here).
    Length/perimeter/width are rounded to the nearest 10m.

    Returns a DataFrame indexed by category (sorted by GEE_legend value, e.g.
    Patch Core, Patch Edge, Other Trees, Trees in Gullies, ...), with numeric
    (unformatted) columns.
    """
    df = pd.read_csv(csv_path).set_index(category_col)
    df = df.loc[sorted(df.index, key=lambda c: _category_sort_key(c, legend))]

    table = pd.DataFrame(index=df.index)
    for col, (source_col, scale, _unit) in PATCH_METRICS_COLUMNS.items():
        values = df[source_col] * scale
        table[col] = values.round(-1) if _unit == "m" else values
    table.index.name = "Category"
    return table


def format_patch_metrics_table(table):
    """Format a patch_metrics_table() DataFrame into display strings."""
    formatted = pd.DataFrame(index=table.index)
    for col, (_source_col, _scale, unit) in PATCH_METRICS_COLUMNS.items():
        if unit == "ha" and col == "Median area":
            formatted[col] = table[col].map(lambda v: f"{v:,.0f} ha" if v >= 10 else f"{v:.1f} ha")
        else:
            formatted[col] = table[col].map(lambda v: f"{v:,.0f} {unit}")
    formatted.index.name = "Category"
    return formatted


def plot_patch_metrics_table(csv_path, category_col="category_name", legend=GEE_legend,
                             palette=LIGHT_SHELTER_PALETTE, other_trees_like="Non-linear Patches",
                             title=None, output_png=None):
    """Render patch_metrics_table() as a coloured table image, one pastel
    row colour per category (from `palette`, via the category's GEE_legend
    value - see plot_category_bars for the same label->colour lookup).

    other_trees_like : if set, 'Other Trees' is recoloured to match this
        other category's colour (mirrors the bar-chart convention set in
        generate_main_plots.py, since 'Other Trees' represents the same kind
        of scattered/irregular growth as e.g. 'Non-linear Patches').
    """
    numeric = patch_metrics_table(csv_path, category_col, legend)
    formatted = format_patch_metrics_table(numeric)

    label_to_value = {}
    for v, lab in legend.items():
        label_to_value.setdefault(lab, v)
    if other_trees_like:
        label_to_value["Other Trees"] = label_to_value[other_trees_like]
    row_colors = [tuple(c / 255 for c in palette.get(label_to_value.get(cat), (230, 230, 230)))
                 for cat in formatted.index]
    header_color = tuple(c / 255 for c in (217, 217, 217))

    n_rows, n_cols = len(formatted), len(formatted.columns) + 1
    fig, ax = plt.subplots(figsize=(1.7 * n_cols, 0.5 * (n_rows + 1)))
    ax.axis("off")
    if title:
        ax.set_title(title, fontsize=14, pad=12)

    cell_text = [[cat] + list(row) for cat, row in zip(formatted.index, formatted.values)]
    col_labels = ["Category"] + list(formatted.columns)
    tbl = ax.table(cellText=cell_text, colLabels=col_labels, cellLoc="right", loc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(11)
    tbl.scale(1, 1.8)
    tbl.auto_set_column_width(list(range(n_cols)))

    for (row, col), cell in tbl.get_celld().items():
        cell.set_edgecolor("black")
        if row == 0:
            cell.set_facecolor(header_color)
            cell.set_text_props(weight="bold")
        else:
            cell.set_facecolor(row_colors[row - 1])
        if col == 0:
            cell.set_text_props(ha="left")
            cell.PAD = 0.05

    fig.tight_layout()
    if output_png:
        os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
        fig.savefig(output_png, dpi=150, bbox_inches="tight")
        print(f"Saved: {output_png}", flush=True)
    return fig


def plot_category_grid(input_dir, suffix, value_range, layout, order_by="default",
                       legend=GEE_legend, pixel_size_m=PIXEL_SIZE_M,
                       palette=SHELTER_PALETTE, suptitle=None, output_png=None):
    """Grid of per-zone bar charts (see plot_category_bars), one panel per
    zone, all sharing the same category row order.

    layout : list of rows, each a list of zone names, e.g.
        [["Western Australia", "Northern Territory", "Queensland", "New South Wales"],
         ["South Australia", "Victoria", "Tasmania", "Australian Capital Territory"]]
        Blank cells (row shorter than the widest row) are left empty.
    order_by : method column used to rank categories for the shared row
        order, computed once across the whole-dataset ALL zone.
    """
    category_order = list(_numeric_table(
        input_dir, suffix, value_range, ALL_ZONE, None, legend, pixel_size_m,
        "hectares", order_by).index)

    nrows = len(layout)
    ncols = max(len(row) for row in layout)
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 4.5, nrows * 5), squeeze=False)

    for r, row_zones in enumerate(layout):
        for c in range(ncols):
            ax = axes[r][c]
            if c >= len(row_zones):
                ax.axis("off")
                continue
            plot_category_bars(input_dir, suffix, value_range, zone=row_zones[c],
                               legend=legend, pixel_size_m=pixel_size_m,
                               category_order=category_order, palette=palette,
                               title=row_zones[c], ax=ax, value_fontsize=7)

    fig.suptitle(suptitle or "Tree Categories by State", fontsize=16)
    fig.tight_layout(rect=(0, 0, 1, 0.96))

    if output_png:
        os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
        fig.savefig(output_png, dpi=150)
        print(f"Saved: {output_png}", flush=True)
    return fig


def plot_category_panels(panels, suptitle=None, output_png=None):
    """Stack several independent plot_category_bars() panels in one figure,
    one per row - e.g. grassland above cropland, each with its own suffix,
    value_range, category_order and palette.

    panels : list of kwarg-dicts for plot_category_bars() (everything except
        `ax`), one per row.
    """
    fig, axes = plt.subplots(len(panels), 1, figsize=(9, 5 * len(panels)), squeeze=False)
    for ax, panel_kwargs in zip(axes[:, 0], panels):
        plot_category_bars(**panel_kwargs, ax=ax)

    if suptitle:
        fig.suptitle(suptitle, fontsize=16)
    fig.tight_layout(rect=(0, 0, 1, 0.96) if suptitle else (0, 0, 1, 1))

    if output_png:
        os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
        fig.savefig(output_png, dpi=150)
        print(f"Saved: {output_png}", flush=True)
    return fig


def category_totals(input_dir, suffix, value_range, zone=ALL_ZONE, methods=None,
                    legend=GEE_legend, pixel_size_m=PIXEL_SIZE_M):
    """Sum hectares across every category in `value_range`, per method.

    Returns a Series indexed by method (e.g. 'default'/'less'/'more').
    """
    table = _numeric_table(input_dir, suffix, value_range, zone, methods,
                           legend, pixel_size_m, "hectares", order_by=None)
    return table.sum(axis=0)


def plot_totals_bars(bars, title=None, output_png=None, value_fontsize=9, ax=None):
    """Single-panel bar chart comparing totals from different (possibly
    unrelated) category_totals() calls - e.g. unsheltered vs. sheltered
    totals for grassland and cropland side by side, on one shared scale.

    bars : list of dicts, each with:
        label       : bar's x-axis label.
        color       : (r, g, b), 0-255.
        input_dir, suffix, value_range : passed to category_totals().
        zone, methods : optional, passed to category_totals().
    ax : optional matplotlib Axes to draw into (e.g. one panel of
        plot_totals_panels()). If omitted, a new standalone figure is
        created (and saved to `output_png`, if given).
    """
    labels, defaults, err_low, err_high, colors = [], [], [], [], []
    for b in bars:
        totals = category_totals(b["input_dir"], b["suffix"], b["value_range"],
                                 zone=b.get("zone", ALL_ZONE), methods=b.get("methods"))
        default = float(totals["default"])
        lower = min(totals["less"], totals["more"])
        upper = max(totals["less"], totals["more"])
        labels.append(b["label"])
        defaults.append(default)
        err_low.append(max(default - lower, 0))
        err_high.append(max(upper - default, 0))
        colors.append(tuple(c / 255 for c in b["color"]))

    title = title or "Category totals"
    standalone = ax is None
    if standalone:
        width = max(6, 1.3 * len(bars), 0.11 * len(title))
        fig, ax = plt.subplots(figsize=(width, 6))
    else:
        fig = ax.figure

    _draw_bars_with_error(ax, labels, defaults, err_low, err_high, colors,
                          "Hectares", title, value_fontsize=value_fontsize, rotation=20)

    if standalone:
        fig.tight_layout()
        if output_png:
            os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
            fig.savefig(output_png, dpi=150)
            print(f"Saved: {output_png}", flush=True)
    return fig


def plot_totals_panels(panels, suptitle=None, output_png=None, share_y=True):
    """Lay out several plot_totals_bars() panels side by side (1 row),
    optionally sharing the y-axis so bar heights are directly comparable.

    panels : list of dicts, each with:
        bars  : passed to plot_totals_bars().
        title : this panel's title (optional).
    """
    fig, axes = plt.subplots(1, len(panels), figsize=(6 * len(panels), 6), sharey=share_y)
    axes = np.atleast_1d(axes)
    for ax, panel in zip(axes, panels):
        plot_totals_bars(panel["bars"], title=panel.get("title"), ax=ax)

    if suptitle:
        fig.suptitle(suptitle, fontsize=16)
    fig.tight_layout(rect=(0, 0, 1, 0.96) if suptitle else (0, 0, 1, 1))

    if output_png:
        os.makedirs(os.path.dirname(os.path.abspath(output_png)), exist_ok=True)
        fig.savefig(output_png, dpi=150)
        print(f"Saved: {output_png}", flush=True)
    return fig


def run(input_dir, suffix, value_range, zone=ALL_ZONE, output_csv=None,
        units="hectares", order_by="default", output_png=None, title=None):
    table = category_area_summary(input_dir, suffix, value_range, zone=zone,
                                   units=units, order_by=order_by)
    print(table.to_string(), flush=True)

    if output_csv:
        os.makedirs(os.path.dirname(os.path.abspath(output_csv)), exist_ok=True)
        table.to_csv(output_csv)
        print(f"Saved: {output_csv}", flush=True)

    if output_png:
        plot_category_bars(input_dir, suffix, value_range, zone=zone,
                           order_by=order_by, output_png=output_png, title=title)
    return table


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Summarise category areas (hectares) across methods, "
                    "from tif_value_counts.py output CSVs.")
    parser.add_argument("--input_dir", required=True,
                        help="Folder containing the per-method CSVs.")
    parser.add_argument("--suffix", required=True,
                        help="Common filename suffix identifying the CSVs to "
                            "compare, e.g. merged_shelter_categories.csv")
    parser.add_argument("--value_range", required=True,
                        help="Category values to include, e.g. '11-19' or "
                            "'30,31,40-49'.")
    parser.add_argument("--zone", default=ALL_ZONE,
                        help="Zone to read from each CSV (default: ALL, the "
                            "whole-dataset total).")
    parser.add_argument("--units", default="hectares",
                        choices=list(UNIT_COLUMNS),
                        help="Units for the table cells (default: hectares).")
    parser.add_argument("--order_by", default="default",
                        help="Method column to sort rows by, descending. "
                            "Pass '' to leave rows in category-value order "
                            "(default: 'default').")
    parser.add_argument("--output_csv", default=None,
                        help="Where to write the summary table.")
    parser.add_argument("--output_png", default=None,
                        help="If given, also save a bar chart (hectares, "
                            "coloured per SHELTER_PALETTE, with less/more "
                            "as error bars around the default method).")
    parser.add_argument("--title", default=None,
                        help="Bar chart title. Defaults to "
                            "'Tree Categories - <zone>' "
                            "('Australia' when --zone is ALL).")
    args = parser.parse_args()

    run(args.input_dir, args.suffix, args.value_range, zone=args.zone,
        output_csv=args.output_csv, units=args.units, order_by=args.order_by,
        output_png=args.output_png, title=args.title)
