#!/usr/bin/env python
"""
generate_gch_plots.py — GCH-derived equivalents of 4 of the generate_main_plots.py charts.

Reads from the GCH v2 "final app" 4-method run (see pbs_scripts/gch_region_methods.{pbs,sh} and
pbs_scripts/gch_value_counts_methods.pbs): each method has its own
/scratch/xe2/cb8590/tif_value_counts_gch_ag_<method>/ folder of value_counts CSVs. This uses the
'_masked' export for each (ag-4km-tile mask baked into the source tif, NLUM applied on top at
count time via tif_value_counts.py's --nlum_tif — see gch_value_counts_methods.pbs), so percentages
are computed over ag-area-valid pixels only:
    less_windmethod    -> 'less'    (MOST_COMMON, edge 3, mc 500,  height-aware)
    default_windmethod -> 'default' (WINDWARD,    edge 4, mc 1000, height-aware)
    more_windmethod    -> 'more'    (WINDWARD,    edge 5, mc 2000, no height)

Usage:
    python analysis/generate_gch_plots.py

Code generated by Claude, verified by comparing plots with the csvs containing the original data.

"""

from category_area_summary import (
    category_area_summary,
    plot_category_bars,
    plot_totals_panels,
    SHELTER_PALETTE,
)
from generate_main_plots import SHELTER_ORDER
from shelterbelts.indices.shelter_categories import shelter_categories_cmap

import os

GCH_ROOT = "/scratch/xe2/cb8590/tif_value_counts_gch_ag"
OUT_DIR = "/scratch/xe2/cb8590/tif_value_counts_gch_ag_plots"
METHOD_BY_LABEL = {"less": "less_windmethod", "default": "default_windmethod", "more": "more_windmethod"}


def _csv(label, datatype):
    method = METHOD_BY_LABEL[label]
    return f"{GCH_ROOT}_{method}/gch_{method}_merged_{datatype}_masked_value_counts.csv"


SHELTER_CATEGORIES_METHODS = {label: _csv(label, "shelter_categories") for label in METHOD_BY_LABEL}
OPPORTUNITIES_METHODS = {label: _csv(label, "opportunities") for label in METHOD_BY_LABEL}

TITLE_SUFFIX = " (GCH)"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    # 1. Tree categories (11-19), Australia-wide.
    out_stub = f"{OUT_DIR}/global_11-19_percentmethod_merged_shelter_categories_hectares"
    table = category_area_summary(None, None, "11-19", methods=SHELTER_CATEGORIES_METHODS,
                                   units="hectares", order_by="default")
    table.to_csv(f"{out_stub}.csv")
    print(f"Saved: {out_stub}.csv")
    plot_category_bars(None, None, "11-19", methods=SHELTER_CATEGORIES_METHODS,
                        palette=SHELTER_PALETTE, order_by="default",
                        title=f"Tree Categories - Australia{TITLE_SUFFIX}",
                        output_png=f"{out_stub}.png")

    # 2. Grassland categories (30-39), Australia-wide. 'less' (percentmethod)
    # has no tree-type breakdown, so its tree-type bars read as 0.
    grassland_order = ["Unsheltered Grassland"] + [s.format(kind="Grassland") for s in SHELTER_ORDER]
    out_stub = f"{OUT_DIR}/global_30-39_windmethod_merged_shelter_categories_hectares"
    table = category_area_summary(None, None, "30,33-39", methods=SHELTER_CATEGORIES_METHODS,
                                   units="hectares", order_by=None)
    table = table.reindex(grassland_order)
    table.to_csv(f"{out_stub}.csv")
    print(f"Saved: {out_stub}.csv")
    plot_category_bars(None, None, "30,33-39", methods=SHELTER_CATEGORIES_METHODS,
                        category_order=grassland_order, palette=shelter_categories_cmap,
                        title=f"Grassland Categories - Australia{TITLE_SUFFIX}",
                        output_png=f"{out_stub}.png")

    # 3. Planting opportunities vs existing shelter, near gullies and roads.
    def gullies_roads_bars(methods):
        return [
            dict(label="Trees in Gullies", color=shelter_categories_cmap[15],
                 input_dir=None, suffix=None, value_range="15", methods=methods),
            dict(label="Trees next to Roads", color=shelter_categories_cmap[17],
                 input_dir=None, suffix=None, value_range="17", methods=methods),
            dict(label="Sheltered by Trees in Gullies", color=shelter_categories_cmap[35],
                 input_dir=None, suffix=None, value_range="35,45", methods=methods),
            dict(label="Sheltered by Trees next to Roads", color=shelter_categories_cmap[37],
                 input_dir=None, suffix=None, value_range="37,47", methods=methods),
        ]

    plot_totals_panels(
        panels=[
            dict(bars=gullies_roads_bars(OPPORTUNITIES_METHODS),
                 title=f"Planting Opportunities - Australia{TITLE_SUFFIX}"),
            dict(bars=gullies_roads_bars(SHELTER_CATEGORIES_METHODS),
                 title=f"Existing Shelter - Australia{TITLE_SUFFIX}"),
        ],
        output_png=f"{OUT_DIR}/global_opportunities_vs_shelter_gullies_roads_hectares.png",
    )

    # 4. Sheltered vs unsheltered totals for grassland and cropland.
    from category_area_summary import plot_totals_bars, CROPLAND_PALETTE
    from generate_main_plots import _darken

    grassland_sheltered_color = _darken(shelter_categories_cmap[30], 0.35)
    cropland_sheltered_color = _darken(CROPLAND_PALETTE[40], 0.35)
    plot_totals_bars(
        bars=[
            dict(label="Unsheltered Grassland", color=shelter_categories_cmap[30],
                 input_dir=None, suffix=None, value_range="30", methods=SHELTER_CATEGORIES_METHODS),
            dict(label="Unsheltered Cropland", color=CROPLAND_PALETTE[40],
                 input_dir=None, suffix=None, value_range="40", methods=SHELTER_CATEGORIES_METHODS),
            dict(label="Sheltered Grassland (total)", color=grassland_sheltered_color,
                 input_dir=None, suffix=None, value_range="32-39", methods=SHELTER_CATEGORIES_METHODS),
            dict(label="Sheltered Cropland (total)", color=cropland_sheltered_color,
                 input_dir=None, suffix=None, value_range="42-49", methods=SHELTER_CATEGORIES_METHODS),
        ],
        title=f"Sheltered vs Unsheltered Totals - Australia{TITLE_SUFFIX}",
        output_png=f"{OUT_DIR}/global_sheltered_vs_unsheltered_totals_hectares.png",
    )


if __name__ == "__main__":
    main()
