#!/usr/bin/env python
"""
Add the percentage sheltered attribute to each zone of a .gpkg.

Usage:
    python zone_shelter_percentage.py \
        --gpkg outdir/tif_value_counts_ag/grdc/grdc_regions.gpkg \
        --zone_col AEZ \
        --csv outdir/tif_value_counts_ag/grdc/default_windmethod_merged_shelter_categories.csv \
        --grassland_col pct_sheltered_grassland \
        --cropland_col pct_sheltered_cropland

Generated by Claude, verified in QGIS
"""

import argparse
import os

import fiona
import geopandas as gpd
import pandas as pd

# Grassland: 30 = unsheltered, 32-39 = sheltered (32 generic + 33-39 by tree type).
GRASSLAND_UNSHELTERED = [30]
GRASSLAND_SHELTERED = [32, 33, 34, 35, 36, 37, 38, 39]

# Cropland: 40 = unsheltered, 42-49 = sheltered (42 generic + 43-49 by tree type).
CROPLAND_UNSHELTERED = [40]
CROPLAND_SHELTERED = [42, 43, 44, 45, 46, 47, 48, 49]


def zone_sheltered_percentage(csv_path, unsheltered_values, sheltered_values):
    """Per-zone % sheltered = sheltered / (sheltered + unsheltered) * 100.

    Returns a {zone_name: percentage} dict (zone omitted if it has no
    grassland/cropland pixels at all, i.e. total == 0).
    """
    df = pd.read_csv(csv_path)
    df = df[df["value"].isin(unsheltered_values + sheltered_values)]

    percentages = {}
    for zone, group in df.groupby("zone"):
        unsheltered = group.loc[group["value"].isin(unsheltered_values), "count"].sum()
        sheltered = group.loc[group["value"].isin(sheltered_values), "count"].sum()
        total = unsheltered + sheltered
        if total > 0:
            percentages[zone] = round(100 * sheltered / total, 2)
    return percentages


def add_shelter_percentages(gpkg_path, zone_col, csv_path, grassland_col, cropland_col,
                            output_gpkg=None, exclude_zones=None):
    # gpkg files can hold multiple named layers; read/write the same one so
    # this doesn't silently create a second, differently-named layer.
    layers = fiona.listlayers(gpkg_path)
    if len(layers) != 1:
        raise SystemExit(f"Expected exactly one layer in {gpkg_path}, found {layers} - "
                         "pass the right one explicitly if this is intentional.")
    layer = layers[0]

    gdf = gpd.read_file(gpkg_path, layer=layer)

    if exclude_zones:
        n_before = len(gdf)
        missing_excludes = set(exclude_zones) - set(gdf[zone_col])
        if missing_excludes:
            raise SystemExit(f"--exclude_zones not found in {zone_col}: {sorted(missing_excludes)}")
        gdf = gdf[~gdf[zone_col].isin(exclude_zones)].reset_index(drop=True)
        print(f"Excluded {sorted(exclude_zones)}: {n_before} -> {len(gdf)} polygons", flush=True)

    grassland_pct = zone_sheltered_percentage(csv_path, GRASSLAND_UNSHELTERED, GRASSLAND_SHELTERED)
    cropland_pct = zone_sheltered_percentage(csv_path, CROPLAND_UNSHELTERED, CROPLAND_SHELTERED)

    gdf[grassland_col] = gdf[zone_col].map(grassland_pct)
    gdf[cropland_col] = gdf[zone_col].map(cropland_pct)

    missing = sorted(set(gdf[zone_col]) - set(grassland_pct) - set(cropland_pct))
    if missing:
        print(f"Warning: no matching rows in {csv_path} for zones: {missing}", flush=True)

    output_gpkg = output_gpkg or gpkg_path
    if output_gpkg == gpkg_path:
        # Overwrite the whole file (not just the layer) so no stale layers survive.
        os.remove(gpkg_path)
    gdf.to_file(output_gpkg, driver="GPKG", layer=layer)
    print(f"Saved: {output_gpkg} layer '{layer}' (+{grassland_col}, +{cropland_col})", flush=True)
    return gdf


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Add % sheltered grassland/cropland columns to a zones gpkg, "
                    "computed from a tif_value_counts.py output CSV.")
    parser.add_argument("--gpkg", required=True, help="Zones polygon file to update.")
    parser.add_argument("--zone_col", required=True,
                        help="Column in --gpkg matching the CSV's 'zone' values, e.g. AEZ.")
    parser.add_argument("--csv", required=True,
                        help="tif_value_counts.py output CSV to compute percentages from, "
                            "e.g. default_windmethod_merged_shelter_categories.csv")
    parser.add_argument("--grassland_col", default="pct_sheltered_grassland",
                        help="Output column name for grassland (default: pct_sheltered_grassland).")
    parser.add_argument("--cropland_col", default="pct_sheltered_cropland",
                        help="Output column name for cropland (default: pct_sheltered_cropland).")
    parser.add_argument("--output_gpkg", default=None,
                        help="Where to write the updated gpkg (default: overwrite --gpkg).")
    parser.add_argument("--exclude_zones", default=None,
                        help="Comma-separated zone names to drop entirely from the gpkg "
                            "before computing percentages, e.g. 'WA Mallee,WA Ord'.")
    args = parser.parse_args()

    exclude_zones = [z.strip() for z in args.exclude_zones.split(",")] if args.exclude_zones else None
    add_shelter_percentages(args.gpkg, args.zone_col, args.csv,
                            args.grassland_col, args.cropland_col, args.output_gpkg,
                            exclude_zones=exclude_zones)
